#!/usr/bin/env zsh

source INPUT_BASE_DIRECTORY
./exec-file-py --input-data \
    $INPUT_BASE_DIRECTORY/real-world-patches/realworldpatches.csv \
    --output $INPUT_BASE_DIRECTORY/output --plot plot-all-patches.R

