#!/usr/bin/env zsh

source INPUT_BASE_DIRECTORY
./exec-file-py --input-data \
    $INPUT_BASE_DIRECTORY/synchronization-time-patch-idle/synchronization-time-patch-idle.duckdb \
    --output $INPUT_BASE_DIRECTORY/output --plot plot-synchronization-time-patch-boxplot-idle.R

