#!/usr/bin/env zsh

set -evu

SCRIPT_DIR=${0:a:h}

# Redis Cluster real-world patches
cd ${SCRIPT_DIR}/real-world-patches/redis-cluster
./setup
cd ${SCRIPT_DIR}/real-world-patches/redis-cluster/crawl-redis
./do
cd ..
./experiment

